# ==============================================================================
#
#  ERDF_CF_Spain_NUTS2_1989_2020 — ERDF and Cohesion Fund certified expenditure
#  in Spain by NUTS2 region, programming axis and thematic area, 1989-2020
#
#  Author  : Paulino Montes-Solla
#  ORCID   : https://orcid.org/0000-0002-5608-6080
#  Affil.  : ECOBAS & GCD, Department of Economics
#             University of A Coruña (UDC), A Coruña (Spain)
#  Email   : paulino.montes.solla@udc.es
#  Repo    : https://github.com/paulinoms/ERDF-CF-Spain-NUTS2-1989-2020
#  Version : 1.0
#  Date    : 2026-03-22
#  Licence : Creative Commons Attribution 4.0 International (CC BY 4.0)
#             https://creativecommons.org/licenses/by/4.0/
#
# ------------------------------------------------------------------------------
#  DESCRIPTION
#  This script fully reproduces the dataset of certified expenditure from the
#  European Regional Development Fund (ERDF) and the Cohesion Fund (CF) in
#  Spain, disaggregated by Autonomous Community (NUTS2 region), execution year,
#  programming axis, and thematic area, for programming periods 1989-1993,
#  1994-1999, 2000-2006, 2007-2013 and 2014-2020.
#  Monetary values are expressed in thousands of euros at constant 2000 prices
#  (m_eur00) and at constant 2020 prices (m_eur2020).
#
# ------------------------------------------------------------------------------
#  REPRODUCIBILITY
#  The script is self-contained: it reads a single source Excel file and
#  generates all outputs deterministically. All monetary conversion factors
#  are hard-coded and documented with their primary sources (EUROSTAT, INE),
#  so results are fully reproducible without an internet connection.
#
# ------------------------------------------------------------------------------
#  HOW TO CITE THIS WORK
#  If you use this dataset or script in an academic publication, please cite:
#
#    Montes-Solla, P. (2026). ERDF and Cohesion Fund Certified Expenditure in
#    Spain by NUTS2 Region, Programming Axis and Thematic Area,
#    1989-2020 [Dataset and R code]. University of A Coruña.
#    https://doi.org/10.5281/zenodo.19171054
#
#  Replace with the actual Zenodo DOI once assigned.
#
# ------------------------------------------------------------------------------
#  REPOSITORY STRUCTURE
#  ├── ERDF_CF_Spain_NUTS2_1989_2020_build.R  <- This script (only file needed)
#  ├── data/
#  │   └── ERDF_CF_Spain_NUTS2_1989_2020_source.xlsx  <- Source data
#  ├── output/                                <- Auto-generated by the script
#  │   ├── ERDF_CF_Spain_NUTS2_1989_2020.rda
#  │   ├── ERDF_CF_Spain_NUTS2_1989_2020.xlsx
#  │   ├── ERDF_CF_Spain_NUTS2_1989_2020.csv
#  │   ├── ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda
#  │   └── ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda
#  ├── README.txt
#  └── LICENSE
#
#  NOTE ON THE SOURCE FILE:
#  'ERDF_CF_Spain_NUTS2_1989_2020_source.xlsx' contains certified expenditure
#  data from the Annual Reports of the DGFC (Ministry of Finance, Spain,
#  1989-2009) and from the EU Cohesion Open Data Platform (2007-2021).
#  Both sources are public institutional data; the Excel workbook is an
#  original compilation by the author. It is included in the repository
#  under the same CC BY 4.0 licence.
#  Estimated size: < 5 MB — within GitHub's 100 MB file limit.
#
# ==============================================================================


# ============================================================
# CLEAR ENVIRONMENT
# ============================================================

rm(list = ls())

if (.Platform$OS.type == "windows") {
  options(encoding = "UTF-8")
  tryCatch(Sys.setlocale("LC_ALL", "Spanish_Spain.UTF-8"),
           error = function(e) Sys.setlocale("LC_ALL", "Spanish"))
}


## ████████████████████████████████████████████████████████████████████████████
##
##  ERDF AND COHESION FUND IN SPAIN — FULL DATABASE RECONSTRUCTION
##  Programming periods: 1989-1993 | 1994-1999 | 2000-2006 |
##                       Cohesion Fund 1989-2006 | 2007-2013 | 2014-2020
##
##  Version : 2.0
##  Date    : 2026-03-22
##
##  PRIMARY SOURCE FILE
##  ─────────────────────────────────────────────────────────────────────────
##  Excel file    : ERDF_CF_Spain_NUTS2_1989_2020_source.xlsx
##  Source sheets : Reg.89-93 | Reg.94-99 | Reg.00-06 | FC.89-06 |
##                  07-13 | 14-20 | IPC/Ptas (monetary conversion factors)
##
##  OUTPUTS GENERATED
##  ─────────────────────────────────────────────────────────────────────────
##  BD_FE_1989_2020          : R data.frame — 1 row per observation
##                             (NUTS2 × Year × Axis × Area)
##                             Monetary columns:
##                               · Gasto_m_eur00   (thousands €, const. 2000)
##                               · Gasto_m_eur2020 (thousands €, const. 2020)
##  ERDF_CF_Spain_NUTS2_1989_2020.rda        : serialised R object
##  pivot_NUTS2_year_EUR2000 : pivot table NUTS2 × Year × Area (€2000)
##  ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda    : serialised R object
##  pivot_NUTS2_year_EUR2020 : pivot table NUTS2 × Year × Area (€2020)
##  ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda    : serialised R object
##  ERDF_CF_Spain_NUTS2_1989_2020.xlsx       : Excel workbook, 7 sheets:
##                                               Main_dataset | Pivot_EUR2000 |
##                                               Pivot_EUR2020 | Summary_areas |
##                                               Summary_period | Metadata |
##                                               Refunds_log
##  ERDF_CF_Spain_NUTS2_1989_2020.csv        : UTF-8 CSV (same as .rda)
##
## ████████████████████████████████████████████████████████████████████████████
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART I — DOCUMENTARY SOURCES BY PROGRAMMING PERIOD
##  ══════════════════════════════════════════════════════════════════════════
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  PERIOD 1989-1993  (Sheet: Reg.89-93 | 585 rows × 12 cols)           │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : Millions of ECU (MECUs)                         │
##  │  Institutional source: Annual Reports of DGFC, Min. Finance, Spain   │
##  │  Page references:                                                    │
##  │    Report 1992 — Obj.1: p.148 / Obj.2: p.181                        │
##  │  Key column   : col[12] = 'Investment MECUs'                         │
##  │  Conversion   : Gasto_m_eur00 = MECUs × EUR/ECU(year) × 1000        │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  PERIOD 1994-1999  (Sheet: Reg.94-99 | 1081 rows × 14 cols)          │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : MECUs (1994-1997) or M€ (1998-2003)             │
##  │  Institutional source: Annual Reports of DGFC, Min. Finance, Spain   │
##  │  Page references:                                                    │
##  │    1993-1995 → Rep.1995 p.282 (Obj.1) / p.310 (Obj.2)               │
##  │    1996      → Rep.1996 p.238 (Obj.1) / p.265 (Obj.2)               │
##  │    1997      → Rep.1997 p.177 (Obj.1) / p.203 (Obj.2)               │
##  │    1998      → Rep.1998 p.144 (Obj.1) / p.170 (Obj.2)               │
##  │    1999      → Rep.1999 p.80  (Obj.1) / p.106 (Obj.2)               │
##  │    2000-2003 → Annual Reports 2000-2003                              │
##  │  Key columns:                                                        │
##  │    col[12] = 'Inv_MECUs'  (1994-1997, when available)                │
##  │    col[14] = 'Expenditure M€' (1998-2003, current euros)             │
##  │  Conversion:                                                         │
##  │    If !is.na(Inv_MECUs)  → MECUs  × EUR/ECU(year) × 1000            │
##  │    If !is.na(Gasto_Meur) → M€ × EUR/ECU(year) × 1000  (pre-2000)    │
##  │                          → M€ × CPI_factor(year) × 1000 (2000+)     │
##  │  NOTE: For 1998-1999 data are in M€ but EUR/ECU is applied (not CPI)  │
##  │  because the reference currency was still the ECU;                   │
##  │  EUR/ECU(1998)=1.00480 and EUR/ECU(1999)=1.00000.                   │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  PERIOD 2000-2006  (Sheet: Reg.00-06 | 858 rows × 14 cols)           │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : M€ current prices                               │
##  │  Institutional source: Annual Reports of DGFC, Min. Finance, Spain   │
##  │  Page references:                                                    │
##  │    2000 → Rep.2000 p.113 (Obj.1) / p.127 (Obj.2)                    │
##  │    2001 → Rep.2001 p.145 (Obj.1) / p.169 (Obj.2)                    │
##  │    2002 → Rep.2002 p.85  (Obj.1) / p.107 (Obj.2)                    │
##  │    2003 → Rep.2003 p.160 (Obj.1) / p.182 (Obj.2)                    │
##  │    2004 → Rep.2004 p.146 (Obj.1) / p.164 (Obj.2)                    │
##  │    2006 → Rep.2006 p.145 (Obj.1) / p.163 (Obj.2) — main source      │
##  │    n+2  → Rep.2007 p.247/265 | Rep.2008 p.128/147 |                 │
##  │           Rep.2009 p.102/121                                         │
##  │  Key column : col[14] = 'Expenditure M€'                             │
##  │  Conversion : M€ × CPI_factor_cumulative(year) × 1000               │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  COHESION FUND 1989-2006  (Sheet: FC.89-06 | 285 rows × 12 cols)     │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : MECUs (pre-2000) or M€ current (2000+)          │
##  │  Institutional source: Annual Reports of DGFC, Cohesion Fund chapters │
##  │  Key column : col[12] = 'Expenditure MECUs' (generic name;           │
##  │               contains MECUs or M€ depending on the year)            │
##  │  Conversion:                                                         │
##  │    Year < 2000 → MECUs × EUR/ECU(year) × 1000                       │
##  │    Year ≥ 2000 → M€   × CPI_factor(year) × 1000                     │
##  │  IMPLEMENTATION NOTE: 'unit' is vectorised (if_else per row) before  │
##  │  being passed to mapply(), because a single sheet contains both      │
##  │  MECUs (pre-2000) and M€ (2000+) rows.                               │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  PERIOD 2007-2013  (Sheet: 07-13 | 8338 rows × 15 cols)              │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : M€ current prices                               │
##  │  Institutional source: EU Cohesion Open Data Platform                │
##  │  URL: https://cohesiondata.ec.europa.eu/                             │
##  │  Downloaded file : 20210909_2007_2013_ejec_dec_anual.xlsx            │
##  │  Download date   : 09/09/2021                                        │
##  │  Verification    : 842 rows, 100% match with sheet 07-13             │
##  │  Key column      : col[15] = 'ExpenditureM€'                         │
##  │  Negative values : certification refunds → set to 0                  │
##  │  Conversion      : M€ × CPI_factor(year) × 1000                     │
##  │  Area columns    : col[10] = Area code / col[11] = Area name         │
##  │  (Thematic area comes directly from source; no reclassification)     │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  PERIOD 2014-2020  (Sheet: 14-20 | 5832 rows × 12 cols)              │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Original currency : M€ current prices                               │
##  │  Institutional source: EU Cohesion Open Data Platform                │
##  │  URL: https://cohesiondata.ec.europa.eu/                             │
##  │  Downloaded file : 20210909_2014_2020_ejec_dec_anual.xlsx            │
##  │  Download date   : 09/09/2021                                        │
##  │  Verification    : 729 rows, 100% match with sheet 14-20             │
##  │  Key column      : col[12] = 'ExpenditureM€'                         │
##  │  Negative values : certification refunds → set to 0                  │
##  │  Conversion      : M€ × CPI_factor(year) × 1000                     │
##  │  Region types    : 1=Less Developed | 2=Transition | 3=More Developed│
##  └──────────────────────────────────────────────────────────────────────┘
##
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART II — MONETARY CONVERSION METHODOLOGY (to € constant 2000)
##  ══════════════════════════════════════════════════════════════════════════
##
##  All monetary values are expressed in thousands of euros at constant 2000
##  prices (m_eur00), regardless of the original currency. Conversion follows
##  two routes depending on the period:
##
##  ROUTE A — Pre-2000 (data in MECUs or M€ linked to ECU):
##  ─────────────────────────────────────────────────────────────────────────
##  Formula:  m€00_t = M_orig_t × EUR/ECU_t × 1000
##
##  Source of EUR/ECU factors:
##    EUROSTAT, table [ert_bil_conv_a] — annual ECU/euro exchange rate
##
##  EUR/ECU factors (verified against the source Excel):
##    ┌──────┬────────────┐
##    │ Year │  EUR/ECU   │
##    ├──────┼────────────┤
##    │ 1989 │ 0.78375500 │
##    │ 1990 │ 0.77777800 │
##    │ 1991 │ 0.77211200 │
##    │ 1992 │ 0.79649500 │
##    │ 1993 │ 0.89625400 │
##    │ 1994 │ 0.95511900 │
##    │ 1995 │ 0.97965000 │
##    │ 1996 │ 0.96611200 │
##    │ 1997 │ 0.99699900 │
##    │ 1998 │ 1.00479700 │
##    │ 1999 │ 1.00000000 │  ← 1 ECU = 1 € (EU Council decision)
##    └──────┴────────────┘
##
##  Verification example (Sheet Reg.89-93, Aragon, Axis 1, 1989):
##    472.973 Mptas × 0.007668 ECU/Pta = 3.627 MECUs
##    3.627 MECUs × 0.783755 EUR/ECU   = 2.843 M€00 × 1000 = 2.843 m€00
##
##  ROUTE B — Post-1999 (data in M€ current prices):
##  ─────────────────────────────────────────────────────────────────────────
##  Formula:  m€00_t = M€_current_t × CPI_factor_cumulative_t × 1000
##
##  Deflator source:
##    INE — Spain CPI, interannual rate (December)
##    URL: https://ine.es/dynt3/inebase/es/index.htm?padre=1368&capsel=3466
##
##  CPI chain (base 2000 = 1.0), cumulative factor = Π(1 + ΔCPI_t):
##    ┌──────┬─────────────┬───────────┐
##    │ Year │  ΔCPI (Dec.)│  Factor   │
##    ├──────┼─────────────┼───────────┤
##    │ 2000 │ base        │ 1.000000  │
##    │ 2001 │  +4.0%      │ 1.040000  │
##    │ 2002 │  +2.7%      │ 1.068080  │
##    │ 2003 │  +4.0%      │ 1.110803  │
##    │ 2004 │  +2.6%      │ 1.139684  │
##    │ 2005 │  +3.2%      │ 1.176154  │
##    │ 2006 │  +3.7%      │ 1.219672  │
##    │ 2007 │  +2.7%      │ 1.252603  │
##    │ 2008 │  +4.2%      │ 1.305212  │
##    │ 2009 │  +1.4%      │ 1.323485  │
##    │ 2010 │  +0.8%      │ 1.334073  │
##    │ 2011 │  +3.0%      │ 1.374095  │
##    │ 2012 │  +2.4%      │ 1.407073  │
##    │ 2013 │  +2.9%      │ 1.447879  │
##    │ 2014 │  +0.3%      │ 1.452222  │
##    │ 2015 │  -1.0%      │ 1.437700  │
##    │ 2016 │   0.0%      │ 1.437700  │
##    │ 2017 │  +1.6%      │ 1.460703  │
##    │ 2018 │  +1.1%      │ 1.476771  │
##    │ 2019 │  +1.2%      │ 1.494492  │
##    │ 2020 │  +0.8%      │ 1.506448  │
##    │ 2021 │  -0.5%      │ 1.498916  │  ← n+2 payments of 2014-2020 only
##    └──────┴─────────────┴───────────┘
##
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART III — DEFLATION TO € CONSTANT 2020 PRICES
##  ══════════════════════════════════════════════════════════════════════════
##
##  Formula:  Gasto_m_eur2020 = Gasto_m_eur00 × CPI_DEFLATOR_2000_2020
##
##  The deflator is computed by chaining the same CPI annual rates used in
##  the original conversion (methodological consistency):
##
##    CPI_DEFLATOR_2000_2020 = Π_{t=2001}^{2020} (1 + ΔCPI_t)
##                           = 1.50644811  (verified value)
##
##  This means 1 € of 2000 is equivalent to ~1.5064 € of 2020.
##
##  Source: INE — Spain CPI, interannual December rate.
##  URL: https://ine.es/dynt3/inebase/es/index.htm?padre=1368&capsel=3466
##
##  METHODOLOGICAL NOTE — CPI vs GDP deflator:
##  Since post-1999 data were originally deflated using the CPI (not the GDP
##  deflator), applying the same CPI in the reverse direction guarantees
##  consistency. Using the GDP deflator instead would underestimate values in
##  €2020 by approximately 15%.
##
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART IV — THEMATIC CLASSIFICATION TABLE (Axis → Area, 1989-2006)
##  ══════════════════════════════════════════════════════════════════════════
##
##  For periods 1989-2006 the thematic area is not coded in the source;
##  it is inferred from the axis name (Nom_Eje) via a direct correspondence
##  table (tabla_areas). This approach is more robust than regex when axis
##  names are stable and known a priori.
##
##  For 2007-2020, the thematic area code comes directly from the source data
##  and no reclassification is applied.
##
##  The 7 thematic areas:
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 1 — TRANSPORT INFRASTRUCTURE  (Narea = 1)                      │
##  ├──────────────────────────────────────────────────────────────────────┤
##  │  Axes assigned (1989-2006):                                          │
##  │    - "Integracion y articulacion territorial"                        │
##  │    - "Mejora de la Red de Comunicaciones"                            │
##  │    - "Desarrollo de la Red de Transportes"                           │
##  │    - "Redes de Transporte y Energia"                                 │
##  │    - "Infraestructuras"                                              │
##  │                                                                      │
##  │  CRITICAL NOTE: In the v4-regex script, axis                         │
##  │  "Infraestructura de apoyo a la actividad economica" is classified   │
##  │  as Area 1. In this script it is assigned to Area 3. Verify before   │
##  │  combining results from both scripts.                                │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 2 — PRODUCTIVE ACTIVITIES  (Narea = 2)                         │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 3 — LOCAL AND URBAN DEVELOPMENT  (Narea = 3)                   │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 4 — ENERGY AND ENVIRONMENT  (Narea = 4)                        │
##  │  NOTE: In v4-regex this is category 5. Verify before combining.      │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 5 — KNOWLEDGE ECONOMY (R&D, INNOVATION)  (Narea = 5)           │
##  │  NOTE: In v4-regex this is category 4. Verify before combining.      │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 6 — COMMUNICATIONS AND DIGITALISATION  (Narea = 6)             │
##  └──────────────────────────────────────────────────────────────────────┘
##
##  ┌──────────────────────────────────────────────────────────────────────┐
##  │  AREA 7 — TECHNICAL ASSISTANCE  (Narea = 7)                          │
##  └──────────────────────────────────────────────────────────────────────┘
##
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART V — TREATMENT OF NEGATIVE VALUES
##  ══════════════════════════════════════════════════════════════════════════
##
##  In periods 2007-2013 and 2014-2020, the EU Cohesion Open Data Platform
##  may include negative expenditure values. These correspond to refunds of
##  previously declared certifications (financial corrections, reimbursements).
##
##  Treatment applied:  pmax(as.numeric(ExpenditureM€), 0)
##  All negative values are replaced with 0 BEFORE monetary conversion.
##  A log of all negative records is exported to the output Excel workbook
##  (sheet "Refunds_log") for full traceability.
##
##
##  ══════════════════════════════════════════════════════════════════════════
##  PART VI — GLOBAL NORMALISATION OF AREA NAMES
##  ══════════════════════════════════════════════════════════════════════════
##
##  Before exporting, two global normalisations are applied to the 'Area'
##  column to ensure consistency across all programming periods:
##
##  1. Area 6 — Communications:
##     Pattern: (?i)^comunicaci
##     → "Comunicaciones y digitalizacion"
##     Unifies typographic variants present in 2014-2020 source data.
##
##  2. Area 7 — Technical assistance:
##     Pattern: str_to_lower == "asistencia tecnica"
##     → "Asistencia tecnica"
##     Unifies capitalisation variants present in 2007-2013 source data.
##
## ████████████████████████████████████████████████████████████████████████████


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 · SETUP: working directory and packages
# ─────────────────────────────────────────────────────────────────────────────

# ADJUST this path to the directory containing the source Excel file
setwd("G:/Mi unidad/- LINO DOCS -/04. PROCESANDO/01 - Futuros Art\u00edculos/2026 Saturation Index")

packages_needed <- c("readxl", "dplyr", "tidyr", "writexl", "stringr", "tibble")
new_packages    <- packages_needed[!packages_needed %in% installed.packages()[, "Package"]]
if (length(new_packages)) install.packages(new_packages)
invisible(lapply(packages_needed, library, character.only = TRUE))

SOURCE_FILE   <- "ERDF_CF_Spain_NUTS2_1989_2020_source.xlsx"  # input Excel
CODEBOOK_FILE <- "ERDF_CF_Spain_NUTS2_1989_2020_codebook.xlsx" # documented output

if (!file.exists(SOURCE_FILE))
  stop("ERROR: File not found: '", SOURCE_FILE, "'\nDirectory: ", getwd())

cat("\n========================================================\n")
cat("  ERDF + CF SPAIN — DATABASE RECONSTRUCTION\n")
cat("  Source  :", SOURCE_FILE, "\n")
cat("  Dir     :", getwd(), "\n")
cat("========================================================\n\n")

# Detect the CPI/exchange-rate sheet robustly (tolerates Unicode variants)
all_sheets <- excel_sheets(SOURCE_FILE)
cpi_sheet  <- all_sheets[str_detect(all_sheets, "(?i)IPC|Ptas")][1]
cat("CPI sheet detected:", cpi_sheet, "\n\n")

# Helper: force exactly 2 decimal places on all double columns before export
round_2dec <- function(df) {
  df |> mutate(across(where(is.double), ~round(., 2)))
}


# ── CPI deflator: €constant 2000 → €constant 2020 ────────────────────────────
# Chain of CPI annual rates (INE Spain, December interannual, base 2000 = 1.0):
#   CPI_DEFLATOR = Π_{t=2001}^{2020} (1 + ΔCPI_t)
# Same rates as those used in the original current-€ to €2000 conversion:
cpi_rates_2000_2020 <- c(
  "2001" = 0.040, "2002" = 0.027, "2003" = 0.040, "2004" = 0.026,
  "2005" = 0.032, "2006" = 0.037, "2007" = 0.027, "2008" = 0.042,
  "2009" = 0.014, "2010" = 0.008, "2011" = 0.030, "2012" = 0.024,
  "2013" = 0.029, "2014" = 0.003, "2015" = -0.010, "2016" = 0.000,
  "2017" = 0.016, "2018" = 0.011, "2019" = 0.012, "2020" = 0.008
)
CPI_DEFLATOR_2000_2020 <- Reduce(function(acc, r) acc * (1 + r),
                                  cpi_rates_2000_2020,
                                  accumulate = FALSE)
# Verifiable result: 1.50644811456...
cat(sprintf("CPI deflator EUR2000 -> EUR2020 : %.10f\n", CPI_DEFLATOR_2000_2020))
cat(sprintf("  (1 EUR of 2000 = %.4f EUR of 2020)\n\n", CPI_DEFLATOR_2000_2020))


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 · MONETARY CONVERSION TABLES
# ─────────────────────────────────────────────────────────────────────────────
# Reads from the CPI/Ptas sheet two sets of conversion factors:
#   (a) EUR/ECU annual exchange rates (EUROSTAT [ert_bil_conv_a])
#   (b) Cumulative CPI factor (INE Spain, base 2000 = 1.0)
# Both are merged into conv_master — the single conversion table used
# throughout the script.
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Loading monetary conversion factors ...\n")

raw_cpi <- read_excel(SOURCE_FILE, sheet = cpi_sheet, col_names = FALSE)

# EUR/ECU factors: rows 2-35, columns 9-10 of the Excel sheet
# (fixed position based on the IPC/Ptas sheet layout)
eur_ecu_rates <- raw_cpi[2:35, 9:10] |>
  setNames(c("Year", "eur_per_ecu")) |>
  mutate(across(everything(), as.numeric)) |>
  filter(!is.na(Year)) |>
  distinct(Year, .keep_all = TRUE)

# Cumulative CPI factor: rows 13-35, columns 9-12
# Column 10 ('CPI_factor') contains the chained factor (base 2000 = 1.0)
# Columns 11-12 are auxiliary and not used
cpi_factors <- raw_cpi[13:35, 9:12] |>
  setNames(c("Year", "CPI_factor", "m", "d")) |>
  mutate(across(c(Year, CPI_factor), as.numeric)) |>
  filter(!is.na(Year))

# Master conversion table: EUR/ECU rates joined with CPI factors
conv_master <- eur_ecu_rates |>
  full_join(cpi_factors |> select(Year, CPI_factor), by = "Year") |>
  arrange(Year) |>
  distinct(Year, .keep_all = TRUE)

stopifnot("conv_master is empty"  = nrow(conv_master) > 0,
          "Year 2000 not found"   = 2000 %in% conv_master$Year)

cat("  conv_master:", min(conv_master$Year), "-",
    max(conv_master$Year, na.rm = TRUE), "| rows:", nrow(conv_master), "\n")


# ── Scalar conversion function ────────────────────────────────────────────────
# Converts a single value from the original currency to thousands of constant
# 2000 euros. Implements both conversion routes (see Part II):
#   · "MEcus"  → always uses EUR/ECU (regardless of year)
#   · "MEuros" → uses EUR/ECU if year < 2000 (ECU-linked euros)
#              → uses CPI_factor if year >= 2000 (real current euros)
# Returns NA with a warning if the year is not in conv_master.
convert_to_eur00 <- function(value, year, unit, conv) {
  if (is.na(value) | is.na(year)) return(NA_real_)
  if (value == 0) return(0)
  f <- conv[conv$Year == year, ]
  if (nrow(f) == 0) { warning("No factor for year ", year); return(NA_real_) }
  f <- f[1, ]
  switch(as.character(unit),
         "MEcus"  = as.numeric(value * f$eur_per_ecu * 1000),
         "MEuros" = if (year < 2000) {
           as.numeric(value * f$eur_per_ecu  * 1000)
         } else {
           as.numeric(value * f$CPI_factor   * 1000)
         },
         { warning("Unknown unit: ", unit); NA_real_ }
  )
}

# ── Vectorised wrapper ────────────────────────────────────────────────────────
# Applies convert_to_eur00() row by row via mapply().
# IMPORTANT: 'u' must be a SCALAR constant for the entire batch of rows.
# If the unit varies per row (Cohesion Fund sheet), do NOT use this function;
# use mapply() directly with 'u' as a vector (see Section 7).
conv_vec <- function(v, y, u, conv) {
  as.numeric(mapply(convert_to_eur00, value = v, year = y,
                    MoreArgs = list(unit = u, conv = conv),
                    SIMPLIFY = TRUE))
}
cat("  Function convert_to_eur00() defined\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 · AXIS → THEMATIC AREA CLASSIFICATION TABLE (1989-2006)
# ─────────────────────────────────────────────────────────────────────────────
# Each row defines the mapping from an axis name (Eje, as it appears in the
# source Excel) to the thematic area code and name.
# The join is applied in Sections 4-7 as: left_join(axis_areas, by = "Eje")
#
# Axes not found in this table will have Narea = NA in the final dataset.
# Check the Narea column in the validation step (Section 11).
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Building axis-to-area classification table ...\n")

axis_areas <- tribble(
  ~Eje,                                                                            ~Narea, ~Area,

  # ── AREA 1: TRANSPORT INFRASTRUCTURE ─────────────────────────────────
  "Integraci\u00f3n y articulaci\u00f3n territorial",                                1L, "Infraestructuras",
  "Mejora de la Red de Comunicaciones",                                             1L, "Infraestructuras",
  "Desarrollo de la Red de Transportes",                                            1L, "Infraestructuras",
  "Redes de Transporte y Energ\u00eda",                                              1L, "Infraestructuras",
  "Infraestructuras",                                                               1L, "Infraestructuras",

  # ── AREA 2: PRODUCTIVE ACTIVITIES ────────────────────────────────────
  "Industria, servicios y artesan\u00eda",                                          2L, "Actividades productivas",
  "Turismo",                                                                        2L, "Actividades productivas",
  "Creaci\u00f3n y desarrollo de Activ. Productivas",                               2L, "Actividades productivas",
  "Desarrollo del tejido econ\u00f3mico",                                           2L, "Actividades productivas",
  "Apoyo al empleo y a la Compititividad de las Empresas",                         2L, "Actividades productivas",
  "Mejora de la Competitividad y Desarrollo del Tejido Productivo",                2L, "Actividades productivas",
  "Mejora de la Competitividad, el Empleo y Desarrollo",                           2L, "Actividades productivas",

  # ── AREA 3: LOCAL AND URBAN DEVELOPMENT ──────────────────────────────
  # NOTE: "Infraestructura de apoyo..." assigned here to Area 3.
  # In the v4-regex script it belongs to Area 1. Verify before combining.
  "Infraestructura de apoyo a la actividad econ\u00f3mica",                        3L, "Desarrollo local y urbano",
  "Desarrollo Local y Urbano",                                                     3L, "Desarrollo local y urbano",

  # ── AREA 4: ENERGY AND ENVIRONMENT ───────────────────────────────────
  # NOTE: In v4-regex this is category 5. Verify before combining.
  "Protecci\u00f3n y mejora del Medio Ambiente",                                   4L, "Energ\u00eda y medio ambiente",
  "Protecci\u00f3n del Medio Ambiente",                                            4L, "Energ\u00eda y medio ambiente",
  "Medio Ambiente, Entorno Natural y Recurso H\u00eddrico",                        4L, "Energ\u00eda y medio ambiente",
  "Infraestructuras / Medio Ambiente",                                             4L, "Energ\u00eda y medio ambiente",

  # ── AREA 5: KNOWLEDGE ECONOMY (R&D, INNOVATION) ──────────────────────
  # NOTE: In v4-regex this is category 4. Verify before combining.
  "Apoyo a I+D y equipamientos para formaci\u00f3n",                               5L, "Conocimiento",
  "Desarrollo de la Investigaci\u00f3n de la Tecnolog\u00eda e Innovaci\u00f3n",   5L, "Conocimiento",
  "Sociedad Conocimiento (Innovaci\u00f3n, I+D, Soc. Info) y Telec.",              5L, "Conocimiento",
  "Sociedad del Conocimiento (Innovaci\u00f3n, I+D,...)",                          5L, "Conocimiento",

  # ── AREA 6: COMMUNICATIONS AND DIGITALISATION ────────────────────────
  "Desarrollo de Redes de Comunicaciones",                                         6L, "Comunicaci\u00f3n y digitalizaci\u00f3n",

  # ── AREA 7: TECHNICAL ASSISTANCE ─────────────────────────────────────
  "Asistencia t\u00e9cnica",                                                       7L, "Asistencia t\u00e9cnica",
  "Asistencia t\u00e9cnica, Seguimiento e Informaci\u00f3n",                       7L, "Asistencia t\u00e9cnica",
  "Medidas para Preparaci\u00f3n, Evaluaci\u00f3n y Seguimiento",                  7L, "Asistencia t\u00e9cnica"
)
cat("  Axes classified:", nrow(axis_areas), "\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 · Reg.89-93 — ERDF Regional 1989-1994
# ─────────────────────────────────────────────────────────────────────────────
# Source: Annual Reports DGFC. Report 1992 p.148 (Obj.1) and p.181 (Obj.2)
# col[12]: 'Investment MECUs'
# Conversion: Gasto_m_eur00 = Inv_MECUs × EUR/ECU(year) × 1000
#
# Columns renamed by position (not by name) for encoding robustness:
#   col[3]  = Period (name varies; standardised as Period_col)
#   col[5]  = Year (execution year)
#   col[12] = Inv_MECUs (investment in millions of ECU)
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing Reg.89-93 (DGFC 1989-1993) ...\n")

raw_reg89 <- read_excel(SOURCE_FILE, sheet = "Reg.89-93", col_names = TRUE)
names(raw_reg89)[c(3, 5, 12)] <- c("Period_col", "Year", "Inv_MECUs_col")

db_reg89 <- raw_reg89 |>
  select(Marco, CCAA, Periodo = Period_col, Anio = Year, Neje,
         Eje, Inv_MECUs = Inv_MECUs_col) |>
  mutate(Anio     = as.integer(Anio),
         Neje     = as.integer(Neje),
         Inv_MECUs = as.numeric(Inv_MECUs)) |>
  filter(!is.na(CCAA), !is.na(Anio), !is.na(Inv_MECUs)) |>
  mutate(Gasto_m_eur00 = round(conv_vec(Inv_MECUs, Anio, "MEcus", conv_master), 2)) |>
  left_join(axis_areas, by = "Eje") |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  Reg.89-93 ->", nrow(db_reg89), "rows | years",
    min(db_reg89$Anio), "-", max(db_reg89$Anio), "\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 · Reg.94-99 — ERDF Regional 1994-2003
# ─────────────────────────────────────────────────────────────────────────────
# Source: Annual Reports DGFC 1995-2003 (see page references in Part I)
#
# Columns renamed by position:
#   col[3]  = Period_col
#   col[5]  = Year
#   col[12] = Inv_MECUs_col  (available for 1994-1997 only)
#   col[14] = Expend_Meur_col (1998-2003, current euros)
#
# Conversion logic (per row):
#   If Inv_MECUs is not NA → MECUs × EUR/ECU × 1000
#   If Expend_Meur is not NA AND year < 2000 → M€ × EUR/ECU × 1000
#   If Expend_Meur is not NA AND year >= 2000 → M€ × CPI_factor × 1000
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing Reg.94-99 (DGFC 1995-2003) ...\n")

raw_reg94 <- read_excel(SOURCE_FILE, sheet = "Reg.94-99", col_names = TRUE)
names(raw_reg94)[c(3, 5, 12, 14)] <- c("Period_col", "Year", "Inv_MECUs_col", "Expend_Meur_col")

db_reg94 <- raw_reg94 |>
  select(Marco, CCAA, Periodo = Period_col, Anio = Year, Neje, Eje,
         Inv_MECUs  = Inv_MECUs_col,
         Expend_Meur = Expend_Meur_col) |>
  mutate(Anio        = as.integer(Anio),
         Neje        = as.integer(Neje),
         Inv_MECUs   = as.numeric(Inv_MECUs),
         Expend_Meur = as.numeric(Expend_Meur)) |>
  filter(!is.na(CCAA), !is.na(Anio)) |>
  mutate(Gasto_m_eur00 = round(case_when(
    !is.na(Inv_MECUs)   ~ conv_vec(Inv_MECUs,   Anio, "MEcus",  conv_master),
    !is.na(Expend_Meur) ~ conv_vec(Expend_Meur, Anio, "MEuros", conv_master),
    TRUE ~ NA_real_
  ), 2)) |>
  filter(!is.na(Gasto_m_eur00)) |>
  left_join(axis_areas, by = "Eje") |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  Reg.94-99 ->", nrow(db_reg94), "rows | years",
    min(db_reg94$Anio), "-", max(db_reg94$Anio), "\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6 · Reg.00-06 — ERDF Regional 2001-2009
# ─────────────────────────────────────────────────────────────────────────────
# Source: Annual Reports DGFC 2001-2009 (see page references in Part I)
#
# Columns renamed by position:
#   col[3]  = Period_col
#   col[5]  = Year
#   col[14] = Expend_Meur_col (M€ current prices)
#
# Conversion: M€ × CPI_factor(year) × 1000
# (all years >= 2000, so conv_vec with "MEuros" always uses CPI route)
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing Reg.00-06 (DGFC 2001-2009) ...\n")

raw_reg00 <- read_excel(SOURCE_FILE, sheet = "Reg.00-06", col_names = TRUE)
names(raw_reg00)[c(3, 5, 14)] <- c("Period_col", "Year", "Expend_Meur_col")

db_reg00 <- raw_reg00 |>
  select(Marco, CCAA, Periodo = Period_col, Anio = Year, Neje, Eje,
         Expend_Meur = Expend_Meur_col) |>
  mutate(Anio        = as.integer(Anio),
         Neje        = as.integer(Neje),
         Expend_Meur = as.numeric(Expend_Meur)) |>
  filter(!is.na(CCAA), !is.na(Anio), !is.na(Expend_Meur)) |>
  mutate(Gasto_m_eur00 = round(conv_vec(Expend_Meur, Anio, "MEuros", conv_master), 2)) |>
  left_join(axis_areas, by = "Eje") |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  Reg.00-06 ->", nrow(db_reg00), "rows | years",
    min(db_reg00$Anio), "-", max(db_reg00$Anio), "\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 7 · FC.89-06 — Cohesion Fund 1989-2007
# ─────────────────────────────────────────────────────────────────────────────
# Source: Annual Reports DGFC, Cohesion Fund chapters
#
# Columns renamed by position:
#   col[3]  = Period_col
#   col[5]  = Year
#   col[12] = Expend_MECUs_col (MECUs before 2000, M€ current from 2000)
#
# Conversion per row (unit changes by year):
#   Year < 2000 → unit = "MEcus"  → MECUs × EUR/ECU × 1000
#   Year >= 2000 → unit = "MEuros" → M€   × CPI     × 1000
#
# IMPLEMENTATION: mapply() is used directly (NOT conv_vec) because 'unit'
# is a vector that varies per row. conv_vec only accepts a scalar unit.
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing FC.89-06 (Cohesion Fund, DGFC) ...\n")

raw_cf <- read_excel(SOURCE_FILE, sheet = "FC.89-06", col_names = TRUE)
names(raw_cf)[c(3, 5, 12)] <- c("Period_col", "Year", "Expend_MECUs_col")

db_fc <- raw_cf |>
  select(Marco, CCAA, Periodo = Period_col, Anio = Year, Neje, Eje,
         Expend_MECUs = Expend_MECUs_col) |>
  mutate(Anio         = as.integer(Anio),
         Neje         = as.integer(Neje),
         Expend_MECUs = as.numeric(Expend_MECUs)) |>
  filter(!is.na(CCAA), !is.na(Anio), !is.na(Expend_MECUs)) |>
  mutate(
    unit          = if_else(Anio < 2000, "MEcus", "MEuros"),
    Gasto_m_eur00 = round(as.numeric(mapply(
      function(v, y, u) convert_to_eur00(v, y, u, conv_master),
      v = Expend_MECUs, y = Anio, u = unit
    )), 2)
  ) |>
  left_join(axis_areas, by = "Eje") |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  FC.89-06  ->", nrow(db_fc), "rows | years",
    min(db_fc$Anio), "-", max(db_fc$Anio), "\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 8 · Sheet 07-13 — ERDF + CF 2007-2016
# ─────────────────────────────────────────────────────────────────────────────
# Source: EU Cohesion Open Data Platform
#   File: 20210909_2007_2013_ejec_dec_anual.xlsx (downloaded 09/09/2021)
#   Verified: 842 rows, 100% match with sheet 07-13
#
# Thematic area comes directly in columns col[10] and col[11];
# no axis_areas join applied (no reclassification needed).
#
# Columns renamed by position:
#   col[5]  = Year_col       col[6]  = Axis_code    col[7]  = Axis_name
#   col[10] = Area_code      col[11] = Area_name     col[12] = NUTS2_code
#   col[13] = NUTS2_name     col[14] = Expend_EUR    col[15] = Expend_Meur
#
# Negative values: refunds → pmax(., 0) before conversion
# Normalisation: "Asistencia Tecnica" → "Asistencia tecnica"
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing sheet 07-13 (EU Cohesion Open Data 2007-2013) ...\n")

raw_0713 <- read_excel(SOURCE_FILE, sheet = "07-13", col_names = TRUE)
names(raw_0713)[c(5, 6, 7, 10, 11, 12, 13, 14, 15)] <-
  c("Year_col", "Axis_code", "Axis_name",
    "Area_code", "Area_name", "NUTS2_code", "NUTS2_name",
    "Expend_EUR", "Expend_Meur")

# Log of refunds (negative values before truncation)
# The 'Fondo' (Fund) column retains its original name (first column)
refunds_log_07 <- raw_0713 |>
  filter(as.numeric(Expend_EUR) < 0) |>
  transmute(Marco       = as.character(Fondo),
            CCAA        = NUTS2_name,
            Anio        = as.integer(Year_col),
            Eje         = Axis_name,
            Expend_Euros = as.numeric(Expend_EUR),
            Note        = "Certification refund -> set to 0")

cat("  Refunds 07-13:", nrow(refunds_log_07),
    "| total:", round(sum(refunds_log_07$Expend_Euros) / 1e6, 2), "M EUR\n")

db_0713 <- raw_0713 |>
  transmute(
    Marco   = as.character(Fondo),
    CCAA    = NUTS2_name,
    Periodo = "2007-2013",
    Anio    = as.integer(Year_col),
    Neje    = as.integer(Axis_code),
    Eje     = Axis_name,
    Narea   = as.integer(Area_code),
    Area    = Area_name,
    G       = pmax(as.numeric(Expend_Meur), 0)
  ) |>
  filter(!is.na(CCAA), !is.na(Anio)) |>
  mutate(
    Gasto_m_eur00 = round(conv_vec(G, Anio, "MEuros", conv_master), 2),
    Area = str_replace(Area, "(?i)^asistencia\\s+t.cnica$", "Asistencia t\u00e9cnica")
  ) |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  07-13     ->", nrow(db_0713), "rows | years",
    min(db_0713$Anio), "-", max(db_0713$Anio), "\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 9 · Sheet 14-20 — ERDF 2014-2021
# ─────────────────────────────────────────────────────────────────────────────
# Source: EU Cohesion Open Data Platform
#   File: 20210909_2014_2020_ejec_dec_anual.xlsx (downloaded 09/09/2021)
#   Verified: 729 rows, 100% match with sheet 14-20
#   Region types: 1=Less Developed | 2=Transition | 3=More Developed
#
# Columns renamed by position (col[7] retains its original name):
#   col[1]=Framework  col[2]=NUTS2_code   col[3]=NUTS2_name  col[4]=Year_col
#   col[5]=Axis_code  col[6]=Axis_name    col[8]=OP_name
#   col[9]=Area_code  col[10]=Area_name   col[11]=Expend_EUR  col[12]=Expend_Meur
#
# Negative values: log + pmax(., 0)
# Normalisation: "Comunicacion y digitalizacion" → "Comunicaciones y digitalizacion"
#                "Asistencia Tecnica" → "Asistencia tecnica"
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Processing sheet 14-20 (EU Cohesion Open Data 2014-2020) ...\n")

raw_1420 <- read_excel(SOURCE_FILE, sheet = "14-20", col_names = TRUE)
names(raw_1420)[c(1, 2, 3, 4, 5, 6, 8, 9, 10, 11)] <-
  c("Framework", "NUTS2_code", "NUTS2_name", "Year_col", "Axis_code",
    "Axis_name", "OP_name", "Area_code", "Area_name", "Expend_EUR")
names(raw_1420)[12] <- "Expend_Meur"

refunds_log_14 <- raw_1420 |>
  filter(as.numeric(Expend_EUR) < 0) |>
  transmute(Marco       = Framework,
            CCAA        = NUTS2_name,
            Anio        = as.integer(Year_col),
            Eje         = Axis_name,
            Expend_Euros = as.numeric(Expend_EUR),
            Note        = "Certification refund -> set to 0")

if (nrow(refunds_log_14) > 0) {
  cat("  Refunds 14-20:", nrow(refunds_log_14),
      "| total:", round(sum(refunds_log_14$Expend_Euros) / 1e6, 2), "M EUR\n")
} else {
  cat("  No negative values in sheet 14-20\n")
}

db_1420 <- raw_1420 |>
  transmute(
    Marco   = as.character(Framework),
    CCAA    = NUTS2_name,
    Periodo = "2014-2020",
    Anio    = as.integer(Year_col),
    Neje    = as.integer(Axis_code),
    Eje     = Axis_name,
    Narea   = as.integer(Area_code),
    Area    = Area_name,
    G       = pmax(as.numeric(Expend_Meur), 0)
  ) |>
  filter(!is.na(CCAA), !is.na(Anio)) |>
  mutate(
    Gasto_m_eur00 = round(conv_vec(G, Anio, "MEuros", conv_master), 2),
    Area = if_else(str_detect(Area, "(?i)^comunicaci"),
                  "Comunicaciones y digitalizaci\u00f3n", Area),
    Area = str_replace(Area, "(?i)^asistencia\\s+t.cnica$", "Asistencia t\u00e9cnica")
  ) |>
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Gasto_m_eur00)

cat("  14-20     ->", nrow(db_1420), "rows | years",
    min(db_1420$Anio), "-", max(db_1420$Anio), "\n\n")

refunds_log_total <- bind_rows(refunds_log_07, refunds_log_14)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 10 · FINAL DATASET: BD_FE_1989_2020
# ─────────────────────────────────────────────────────────────────────────────
# All 6 source data frames are merged, global area normalisations applied
# (see Part VI), 2 decimal places enforced, records outside 1989-2020 removed,
# and the constant-2020 column computed.
#
# Final data frame columns:
#   Marco          : programme framework or fund name
#   CCAA           : NUTS2 region name (Autonomous Community)
#   Periodo        : programming period ("1989-1993", ..., "2014-2020")
#   Anio           : execution year (integer, 1989-2020)
#   Neje           : axis number/code
#   Eje            : axis name (original Spanish)
#   Narea          : thematic area code (1-7)
#   Area           : normalised thematic area name
#   Fuente         : source sheet identifier
#   Gasto_m_eur00  : expenditure in thousands of constant 2000 euros (2 dec.)
#   Gasto_m_eur2020: expenditure in thousands of constant 2020 euros (2 dec.)
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Building final dataset BD_FE_1989_2020 ...\n")

BD_FE_1989_2020 <- bind_rows(
  db_reg89 |> mutate(Fuente = "Reg.89-93"),
  db_reg94 |> mutate(Fuente = "Reg.94-99"),
  db_reg00 |> mutate(Fuente = "Reg.00-06"),
  db_fc    |> mutate(Fuente = "FC.89-06"),
  db_0713  |> mutate(Fuente = "07-13"),
  db_1420  |> mutate(Fuente = "14-20")
) |>
  mutate(
    Gasto_m_eur00 = round(as.numeric(Gasto_m_eur00), 2),
    Anio          = as.integer(Anio),
    Narea         = as.integer(Narea),
    Area          = str_trim(Area),
    # Global normalisation Area 6: unify typographic variants
    Area = if_else(str_detect(Area, "(?i)^comunicaci"),
                  "Comunicaciones y digitalizaci\u00f3n", Area),
    # Global normalisation Area 7: unify capitalisation
    Area = if_else(str_to_lower(Area) == "asistencia t\u00e9cnica",
                  "Asistencia t\u00e9cnica", Area)
  ) |>
  filter(!is.na(Gasto_m_eur00), Anio >= 1989, Anio <= 2020) |>
  # Deflate to constant 2020 prices
  # Formula: Gasto_m_eur2020 = Gasto_m_eur00 × CPI_DEFLATOR_2000_2020
  mutate(Gasto_m_eur2020 = round(Gasto_m_eur00 * CPI_DEFLATOR_2000_2020, 2)) |>
  # NOTE: column 'Anio' (no tilde) is kept throughout R processing.
  # Renamed to 'Año' only in export tables (Section 14) using
  # rename("A\u00f1o" = Anio) — the tilde is inside a string where \u00f1 works.
  select(Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area,
         Fuente, Gasto_m_eur00, Gasto_m_eur2020) |>
  arrange(Marco, CCAA, Periodo, Anio, Eje)

cat("  Rows      :", nrow(BD_FE_1989_2020), "\n")
cat("  Years     :", min(BD_FE_1989_2020$Anio), "-",
    max(BD_FE_1989_2020$Anio), "\n")
cat("  NUTS2 (n) :", n_distinct(BD_FE_1989_2020$CCAA), "\n")
cat("  Total kEUR2000 :",
    formatC(round(sum(BD_FE_1989_2020$Gasto_m_eur00)),
            format = "f", digits = 0, big.mark = ",", big.interval = 3L), "\n")
cat("  Total kEUR2020 :",
    formatC(round(sum(BD_FE_1989_2020$Gasto_m_eur2020)),
            format = "f", digits = 0, big.mark = ",", big.interval = 3L), "\n")

# Optional cross-validation against original 'DB' sheet (if present)
available_sheets <- excel_sheets(SOURCE_FILE)
if ("DB" %in% available_sheets) {
  DB_orig  <- read_excel(SOURCE_FILE, sheet = "DB")
  col_orig <- grep("m.*00|m.00", names(DB_orig), value = TRUE, ignore.case = TRUE)[1]
  if (!is.na(col_orig)) {
    year_col_orig <- grep("a.o.ejec|a\u00f1o.ejec", names(DB_orig),
                          ignore.case = TRUE, value = TRUE)[1]
    if (!is.na(year_col_orig)) {
      mask_orig <- as.integer(DB_orig[[year_col_orig]]) >= 1989 &
        as.integer(DB_orig[[year_col_orig]]) <= 2020
      tot_orig  <- sum(as.numeric(DB_orig[[col_orig]][mask_orig]), na.rm = TRUE)
    } else {
      tot_orig <- sum(as.numeric(DB_orig[[col_orig]]), na.rm = TRUE)
    }
    tot_calc <- sum(BD_FE_1989_2020$Gasto_m_eur00, na.rm = TRUE)
    diff_pct <- abs(tot_orig - tot_calc) / abs(tot_orig) * 100
    cat("  Original DB total:", formatC(round(tot_orig), format = "f",
                                        digits = 0, big.mark = ","), "\n")
    cat("  Difference (%)   :", sprintf("%.4f%%\n", diff_pct))
    cat("  ->", if_else(diff_pct < 0.1, "EXCELLENT MATCH", "REVIEW"), "\n")
  }
} else {
  cat("  [INFO] Sheet 'DB' not found in source Excel.\n")
  cat("         Cross-validation skipped (expected with updated source file).\n")
}
cat("\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 11 · VALIDATION CHECKS
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Running validation checks ...\n")

n_neg <- sum(BD_FE_1989_2020$Gasto_m_eur00 < 0, na.rm = TRUE)
cat("  Negative values after treatment:", n_neg,
    if_else(n_neg == 0, "(OK)", "(REVIEW)"), "\n")
cat("  NAs in Gasto_m_eur00           :", sum(is.na(BD_FE_1989_2020$Gasto_m_eur00)), "\n")
cat("  Unclassified axes (NA Narea)   :", sum(is.na(BD_FE_1989_2020$Narea)), "\n")

# Records beyond the n+2 rule (normal under EU regulations; informational only)
out_of_n2 <- BD_FE_1989_2020 |>
  mutate(Period_end = as.integer(str_extract(Periodo, "\\d{4}$")),
         within_n2  = Anio <= (Period_end + 2)) |>
  filter(!within_n2)
cat("  Outside n+2 rule               :", nrow(out_of_n2), "(normal, EU rule)\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 12 · SUMMARY TABLES
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Building summary tables ...\n")

# 12.1 Summary by thematic area (total 1989-2020)
summary_areas <- BD_FE_1989_2020 |>
  group_by(Narea, Area) |>
  summarise(Gasto_m_eur00 = round(sum(Gasto_m_eur00, na.rm = TRUE), 2),
            .groups = "drop") |>
  arrange(Narea)

cat("\n  EXPENDITURE BY THEMATIC AREA (thousands EUR2000, 2 decimals):\n")
cat(sprintf("  %2s  %-38s  %20s\n", "N", "Area", "Expenditure (kEUR00)"))
cat("  ", strrep("-", 64), "\n", sep = "")
for (i in seq_len(nrow(summary_areas))) {
  cat(sprintf("  %2d  %-38s  %20.2f\n",
              summary_areas$Narea[i], summary_areas$Area[i],
              summary_areas$Gasto_m_eur00[i]))
}
cat("  ", strrep("-", 64), "\n", sep = "")
cat(sprintf("  %2s  %-38s  %20.2f\n", "", "TOTAL",
            sum(summary_areas$Gasto_m_eur00)))

# 12.2 Summary by area and programming period
summary_areas_period <- BD_FE_1989_2020 |>
  group_by(Narea, Area, Periodo) |>
  summarise(Gasto_m_eur00 = round(sum(Gasto_m_eur00, na.rm = TRUE), 2),
            .groups = "drop") |>
  arrange(Narea, Periodo)

# 12.3 Pivot table: NUTS2 × Year → columns = thematic areas (€2000)
area_cols <- c("Infraestructuras", "Actividades productivas",
               "Desarrollo local y urbano", "Energ\u00eda y medio ambiente",
               "Conocimiento", "Comunicaciones y digitalizaci\u00f3n",
               "Asistencia t\u00e9cnica")

pivot_NUTS2_year_EUR2000 <- BD_FE_1989_2020 |>
  group_by(CCAA, Anio, Area) |>
  summarise(Gasto_m_eur00 = sum(Gasto_m_eur00, na.rm = TRUE), .groups = "drop") |>
  pivot_wider(names_from  = Area,
              values_from = Gasto_m_eur00,
              values_fill = 0) |>
  select(CCAA, Anio, any_of(area_cols)) |>
  mutate(across(where(is.numeric), ~round(., 2))) |>
  arrange(CCAA, Anio)

cat("\n  Pivot NUTS2 x Year x Area (EUR2000):", nrow(pivot_NUTS2_year_EUR2000),
    "rows x", ncol(pivot_NUTS2_year_EUR2000), "cols\n")

# 12.4 Pivot table: NUTS2 × Year → columns = thematic areas (€2020)
pivot_NUTS2_year_EUR2020 <- BD_FE_1989_2020 |>
  group_by(CCAA, Anio, Area) |>
  summarise(Gasto_m_eur2020 = sum(Gasto_m_eur2020, na.rm = TRUE), .groups = "drop") |>
  pivot_wider(names_from  = Area,
              values_from = Gasto_m_eur2020,
              values_fill = 0) |>
  select(CCAA, Anio, any_of(area_cols)) |>
  mutate(across(where(is.numeric), ~round(., 2))) |>
  arrange(CCAA, Anio)

cat("  Pivot NUTS2 x Year x Area (EUR2020):", nrow(pivot_NUTS2_year_EUR2020),
    "rows x", ncol(pivot_NUTS2_year_EUR2020), "cols\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 13 · METADATA AND SOURCE DOCUMENTATION TABLES
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Building metadata and source tables ...\n")

doc_sources <- tribble(
  ~Programming_period,           ~Source_sheet, ~Data_years, ~Original_unit,   ~Institutional_source,                          ~Page_references,                                                                       ~URL,
  "1989-1993 (Regional ERDF)",   "Reg.89-93",   "1989-1994", "MECUs",          "DGFC Annual Reports, Min. Finance, Spain",      "Report 1992: Obj.1 p.148, Obj.2 p.181",                                               "DGFC/MINHAC (printed)",
  "1994-1999 (Regional ERDF)",   "Reg.94-99",   "1994-2003", "MECUs/M€",       "DGFC Annual Reports, Min. Finance, Spain",      "Rep.1995 p.282/310 | Rep.1996 p.238 | Rep.1997 p.177 | Rep.1998 p.144 | Rep.1999 p.80","DGFC/MINHAC (printed)",
  "2000-2006 (Regional ERDF)",   "Reg.00-06",   "2001-2009", "M€ current",     "DGFC Annual Reports, Min. Finance, Spain",      "Rep.2001 p.145 | Rep.2002 p.85 | Rep.2003 p.160 | Rep.2004 p.146 | Rep.2006 p.145",  "DGFC/MINHAC (printed)",
  "1989-2006 (Cohesion Fund)",   "FC.89-06",    "1989-2007", "MECUs/M€",       "DGFC Annual Reports, Cohesion Fund chapters",   "DGFC annual reports (Cohesion Fund specific chapters)",                                "DGFC/MINHAC (printed)",
  "2007-2013 (ERDF + CF)",       "07-13",       "2007-2016", "M€ current",     "EU Cohesion Open Data Platform",                "20210909_2007_2013_ejec_dec_anual.xlsx (09/09/2021). 842 rows, 100% verified",        "https://cohesiondata.ec.europa.eu/",
  "2014-2020 (ERDF)",            "14-20",       "2014-2021", "M€ current",     "EU Cohesion Open Data Platform",                "20210909_2014_2020_ejec_dec_anual.xlsx (09/09/2021). 729 rows, 100% verified",        "https://cohesiondata.ec.europa.eu/"
)

doc_conversion <- tribble(
  ~Period,          ~Original_unit,  ~Formula_kEUR00,                        ~Factor_source,
  "1989-1999",      "MECUs",         "MECUs x EUR/ECU(year) x 1000",         "EUROSTAT [ert_bil_conv_a]",
  "1998-1999",      "M€",            "M€ x EUR/ECU(year) x 1000",            "EUROSTAT (EUR/ECU98=1.00480; 99=1.00000)",
  "2000",           "M€ current",    "M€ x 1.0 x 1000  [CPI base = 1.0]",   "Base year 2000",
  "2001-2021",      "M€ current",    "M€ x CPI_cumulative(year) x 1000",     "INE Spain CPI (base 2000 = 1.0)",
  "EUR/ECU 1989",   "0.783755",      "-",                                     "EUROSTAT",
  "EUR/ECU 1990",   "0.777778",      "-",                                     "EUROSTAT",
  "EUR/ECU 1991",   "0.772112",      "-",                                     "EUROSTAT",
  "EUR/ECU 1992",   "0.796495",      "-",                                     "EUROSTAT",
  "EUR/ECU 1993",   "0.896254",      "-",                                     "EUROSTAT",
  "EUR/ECU 1994",   "0.955119",      "-",                                     "EUROSTAT",
  "EUR/ECU 1995",   "0.979650",      "-",                                     "EUROSTAT",
  "EUR/ECU 1996",   "0.966112",      "-",                                     "EUROSTAT",
  "EUR/ECU 1997",   "0.996999",      "-",                                     "EUROSTAT",
  "EUR/ECU 1998",   "1.004797",      "-",                                     "EUROSTAT",
  "EUR/ECU 1999",   "1.000000",      "-",                                     "EUROSTAT",
  "CPI 2001",       "1.040000",      "-",                                     "INE",
  "CPI 2002",       "1.068080",      "-",                                     "INE",
  "CPI 2003",       "1.110803",      "-",                                     "INE",
  "CPI 2004",       "1.139684",      "-",                                     "INE",
  "CPI 2005",       "1.176154",      "-",                                     "INE",
  "CPI 2006",       "1.219672",      "-",                                     "INE",
  "CPI 2007",       "1.252603",      "-",                                     "INE",
  "CPI 2008",       "1.305212",      "-",                                     "INE",
  "CPI 2009",       "1.323485",      "-",                                     "INE",
  "CPI 2010",       "1.334073",      "-",                                     "INE",
  "CPI 2011",       "1.374095",      "-",                                     "INE",
  "CPI 2012",       "1.407073",      "-",                                     "INE",
  "CPI 2013",       "1.447879",      "-",                                     "INE",
  "CPI 2014",       "1.452222",      "-",                                     "INE",
  "CPI 2015",       "1.437700",      "-",                                     "INE",
  "CPI 2016",       "1.437700",      "-",                                     "INE",
  "CPI 2017",       "1.460703",      "-",                                     "INE",
  "CPI 2018",       "1.476771",      "-",                                     "INE",
  "CPI 2019",       "1.494492",      "-",                                     "INE",
  "CPI 2020",       "1.506448",      "-",                                     "INE",
  "CPI 2021",       "1.498916",      "-",                                     "INE  (n+2 payments of 2014-2020 only)"
)

metadata <- tribble(
  ~Field,                    ~Value,
  "Dataset",                 "ERDF and CF Certified Expenditure in Spain by NUTS2, Axis and Thematic Area, 1989-2020",
  "R object",                "BD_FE_1989_2020",
  "RDA file",                "ERDF_CF_Spain_NUTS2_1989_2020.rda",
  "Excel output",            "ERDF_CF_Spain_NUTS2_1989_2020.xlsx",
  "Build date",              format(Sys.Date(), "%Y-%m-%d"),
  "Script",                  "ERDF_CF_Spain_NUTS2_1989_2020_build.R",
  "Temporal coverage",       paste(min(BD_FE_1989_2020$Anio), "-", max(BD_FE_1989_2020$Anio)),
  "Programming periods",     "1989-1993 | 1994-1999 | 2000-2006 | 2007-2013 | 2014-2020",
  "Total records",           as.character(nrow(BD_FE_1989_2020)),
  "NUTS2 regions included",  paste(sort(unique(BD_FE_1989_2020$CCAA)), collapse = "; "),
  "Variables",               "Marco, CCAA, Periodo, Anio, Neje, Eje, Narea, Area, Fuente, Gasto_m_eur00, Gasto_m_eur2020",
  "Monetary unit (EUR00)",   "Thousands of euros at constant 2000 prices",
  "Monetary unit (EUR2020)", "Thousands of euros at constant 2020 prices",
  "Decimal places",          "2 decimal places enforced on all numerical outputs",
  "Total expenditure (kEUR00)", format(round(sum(BD_FE_1989_2020$Gasto_m_eur00)), big.mark = ","),
  "CPI deflator 2000->2020", as.character(round(CPI_DEFLATOR_2000_2020, 8)),
  "Source 1989-2006",        "DGFC Annual Reports, Ministry of Finance, Spain",
  "Source 2007-2013",        "EU Cohesion Open Data https://cohesiondata.ec.europa.eu/",
  "Source 2014-2020",        "EU Cohesion Open Data https://cohesiondata.ec.europa.eu/",
  "EUR/ECU source",          "EUROSTAT [ert_bil_conv_a]",
  "CPI source",              "INE Spain https://ine.es/dynt3/inebase/es/index.htm?padre=1368",
  "Licence",                 "CC BY 4.0 — https://creativecommons.org/licenses/by/4.0/",
  "NOTE classification",     "Area 4=Energy&Env, Area 5=Knowledge (reversed vs v4-regex script)",
  "NOTE axis 'Infr.support'","Infraestructura de apoyo... → Area 3 (vs Area 1 in v4-regex)"
)

cat("  Metadata and source tables: OK\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 14 · EXPORT
# ─────────────────────────────────────────────────────────────────────────────

cat("-- Exporting files ...\n")

# Force 2 decimal places and rename Anio -> Año ONLY in export tables.
# rename("A\u00f1o" = Anio): the ñ is inside a text string ("..."),
# where \u00f1 is interpreted correctly by R. Outside strings, \u00f1
# does NOT work as part of an R variable/column identifier.
main_export     <- round_2dec(BD_FE_1989_2020)      |> rename("A\u00f1o" = Anio)
pivot_eur2000   <- round_2dec(pivot_NUTS2_year_EUR2000) |> rename("A\u00f1o" = Anio)
pivot_eur2020   <- round_2dec(pivot_NUTS2_year_EUR2020) |> rename("A\u00f1o" = Anio)
summary_exp     <- round_2dec(summary_areas)
summary_p_exp   <- round_2dec(summary_areas_period)

# A) Serialised R object — load with: load("ERDF_CF_Spain_NUTS2_1989_2020.rda")
save(BD_FE_1989_2020, file = "ERDF_CF_Spain_NUTS2_1989_2020.rda")
cat("  ERDF_CF_Spain_NUTS2_1989_2020.rda\n")

# B) Pivot table EUR2000 as independent R object
save(pivot_NUTS2_year_EUR2000, file = "ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda")
cat("  ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda\n")

# C) Pivot table EUR2020 as independent R object
save(pivot_NUTS2_year_EUR2020, file = "ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda")
cat("  ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda\n")

# D) Main Excel workbook (7 sheets):
#   Main_dataset  : all records (EUR00 and EUR2020), 2 decimal places
#   Pivot_EUR2000 : NUTS2 × Year × Area matrix in €2000
#   Pivot_EUR2020 : NUTS2 × Year × Area matrix in €2020
#   Summary_areas : totals by thematic area
#   Summary_period: totals by area and programming period
#   Metadata      : dataset description and references
#   Refunds_log   : log of negative values set to zero
write_xlsx(
  list(
    "Main_dataset"   = main_export,
    "Pivot_EUR2000"  = pivot_eur2000,
    "Pivot_EUR2020"  = pivot_eur2020,
    "Summary_areas"  = summary_exp,
    "Summary_period" = summary_p_exp,
    "Metadata"       = metadata,
    "Refunds_log"    = refunds_log_total
  ),
  "ERDF_CF_Spain_NUTS2_1989_2020.xlsx"
)
cat("  ERDF_CF_Spain_NUTS2_1989_2020.xlsx  (7 sheets)\n")

# E) UTF-8 CSV
write.csv(BD_FE_1989_2020, "ERDF_CF_Spain_NUTS2_1989_2020.csv",
          row.names = FALSE, fileEncoding = "UTF-8")
cat("  ERDF_CF_Spain_NUTS2_1989_2020.csv\n")

# F) Documented codebook Excel (7 sheets, includes source and conversion docs):
#   Sources_periods    : source documentation per period (see Part I)
#   Conversion_factors : EUR/ECU and CPI factors (see Part II)
#   Main_dataset       : full dataset (EUR00 and EUR2020)
#   Pivot_EUR2000      : NUTS2 × Year × Area in €2000
#   Pivot_EUR2020      : NUTS2 × Year × Area in €2020
#   Summary_areas      : totals by thematic area
#   Metadata           : description, references and classification notes
write_xlsx(
  list(
    "Sources_periods"    = doc_sources,
    "Conversion_factors" = doc_conversion,
    "Main_dataset"       = main_export,
    "Pivot_EUR2000"      = pivot_eur2000,
    "Pivot_EUR2020"      = pivot_eur2020,
    "Summary_areas"      = summary_exp,
    "Metadata"           = metadata
  ),
  CODEBOOK_FILE
)
cat("  ", CODEBOOK_FILE, "(7 sheets)\n\n")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 15 · COMPLETION SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

cat("========================================================\n")
cat("  PROCESS COMPLETED SUCCESSFULLY\n")
cat("========================================================\n")
cat("  Rows              :", nrow(BD_FE_1989_2020), "\n")
cat("  Columns           :", paste(names(BD_FE_1989_2020), collapse = ", "), "\n")
cat("  Years             :", min(BD_FE_1989_2020$Anio), "-",
    max(BD_FE_1989_2020$Anio), "\n")
cat("  Periods           :", paste(unique(BD_FE_1989_2020$Periodo), collapse = " | "), "\n")
cat("  NUTS2 regions (n) :", n_distinct(BD_FE_1989_2020$CCAA), "\n")
cat("  Total kEUR2000    :",
    formatC(round(sum(BD_FE_1989_2020$Gasto_m_eur00)),
            format = "f", digits = 0, big.mark = ",", big.interval = 3L), "\n")
cat("\n  FILES GENERATED:\n")
cat("    ERDF_CF_Spain_NUTS2_1989_2020.rda")
cat("  <- load('ERDF_CF_Spain_NUTS2_1989_2020.rda')\n")
cat("    ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda")
cat("  <- load('ERDF_CF_Spain_NUTS2_pivot_EUR2000.rda')\n")
cat("    ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda")
cat("  <- load('ERDF_CF_Spain_NUTS2_pivot_EUR2020.rda')\n")
cat("    ERDF_CF_Spain_NUTS2_1989_2020.xlsx   <- 7 sheets\n")
cat("    ERDF_CF_Spain_NUTS2_1989_2020.csv    <- UTF-8 CSV\n")
cat("   ", CODEBOOK_FILE, "<- documented codebook\n")
cat("\n  KEY DIFFERENCES VS v4-REGEX SCRIPT:\n")
cat("  1. Source: sheets Reg.*/FC.*/07-13/14-20 (vs datos_*/fc_*)\n")
cat("  2. Classification 1989-2006: direct table (vs regex)\n")
cat("  3. Area 4 = Energy&Env | Area 5 = Knowledge (reversed in v4)\n")
cat("  4. 'Infraestructura de apoyo...' -> Area 3 (Area 1 in v4)\n")
cat("  5. CPI includes 2021 (factor 1.498916) for 2014-2020 n+2\n")
cat("  6. Adds Gasto_m_eur2020 column and EUR2020 pivot table\n")
cat("========================================================\n")
